##### 1. Write a Python Program to Add Two Matrices?

In [1]:
def add_mat(x, y):
    result = [[0,0,0],
              [0,0,0],
              [0,0,0]]
    for i in range(len(x)):
   # iterate through columns
        for j in range(len(x[0])):
            result[i][j] = x[i][j] + y[i][j]

    for r in result:
        print(r)

In [2]:
x = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]

y = [[5,8,1],
     [6,7,3],
     [4,5,9]]

add_mat(x, y)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


##### 2. Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np

def mul_mat(x, y):
    result = np.dot(x,y)
    return result

In [4]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

mul_mat(A, B)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

##### 3. Write a Python Program to Transpose a Matrix?

In [5]:
import numpy as np

def transp_mat(matrix):
    print(f'Original Array:\n{matrix}')
    matrix_transpose = matrix.transpose()
    print(f'Transposed Array:\n{matrix_transpose}')

In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
transp_mat(arr1)

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


##### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
def sort_words(arr):
    words = arr.split()
    words.sort()
    for word in words:
        print(word)

In [8]:
sort_words(arr = input('enter words'))

enter wordsfull stack data science
data
full
science
stack


##### 5. Write a Python Program to Remove Punctuation From a String?

In [9]:
def remove_punc(string):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    rem_punc = ""
    for i in string:
        if i not in punctuations:
            rem_punc = rem_punc + i
    return rem_punc

In [10]:
remove_punc(string= input('enter a string: '))

enter a string: **i@Neur$$$on


'iNeuron'